version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    container_name: api-albums
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always
    environment:
      DB_HOST: "db"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_SSL_MODE: "${DB_SSL_MODE}"
      DB_CONNECT_TIMEOUT: "${DB_CONNECT_TIMEOUT}"
    depends_on:
      - db

  migrate-up:
    image: migrate/migrate
    container_name: migrate-up
    depends_on:
      - db
      - api
    volumes:
      - ./db/migrations:/migrations
    command: ["-path=/migrations", "-database=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up"]

volumes:
  postgres_data: